### ISSUE TITLE
Add backlist tag

### ISSUE THREAD

**Issue by Linuxfy** [KuroZen/r34#10]
Can you add a blacklisted tag?

**Comment by kurozenzen** [comment]
Sorry for the slow response. I would suggest you start using the new app: https://kurozenzen.github.io/r34-react/ (**Tap the little plus**). I rewrote it from the ground up.

Also I forgot the password to that account... 😑

If you find any more issues please post them here: https://github.com/kurozenzen/r34-react/issues
