### ISSUE TITLE
Prevent autoscroll to bottom

### ISSUE THREAD

**Issue by emmalexandria** [KuroZen/r34#5]
When loading more images under a tag, the page will auto scroll down to the bottom of the new images loaded. I was thinking it'd be good to set it up so that it auto scrolls to the start of the newly loaded images, or maybe scroll doesn't change at all.

**Comment by kurozenzen** [comment]
Sorry for the very slow response. Considering the old app is permanently broken and I have a new one here: https://kurozenzen.github.io/r34-react/, let me know if it still happens there. If you are still there 😅 I mean I took half a year to respond😑 Fuck me
