### ISSUE TITLE
searching not working

### ISSUE THREAD

**Issue by ghost** [KuroZen/r34#7]

**Comment by millaqueen** [comment]
hey occasionally i can’t seem to get the search function to work, it just won’t pull anything up or even show tags when i type them

**Comment by mjlee2003** [comment]
> **Describe the bug**
> Searching just doesn't work
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Device**
> The device you saw the bug on.
> 
> **Additional information**
> it says CORS
